import { monthHash } from "@/utils/hashs/monthHash";

export const combustiveisFilters = {
  years: ["2019", "2020", "2021", "2022", "2023", "2024"],

  additionalFilters: [
    {
      label: "Mês",
      options: [],
      selected: [],
      hash: monthHash,
    },
    {
      label: "PRODUTO",
      options: [
        "Gasolina Comum",
        "Gasolina Aditivada",
        "Etanol Hidratado",
        "Óleo Diesel S10",
        "Óleo Diesel S500",
        "GLP",
        "GNV",
      ],
      selected: ["Óleo Diesel S10"],
      allowMultiple: false,
    },
    {
      label: "REGIÃO",
      options: ["Norte", "Nordeste", "Centro-Oeste", "Sudeste", "Sul"],
      selected: [],
      allowMultiple: false,
    },
    {
      label: "ESTADO",
      options: [
        "AC",
        "AL",
        "AM",
        "AP",
        "BA",
        "CE",
        "DF",
        "ES",
        "GO",
        "MA",
        "MG",
        "MS",
        "MT",
        "PA",
        "PB",
        "PE",
        "PI",
        "PR",
        "RJ",
        "RN",
        "RO",
        "RR",
        "RS",
        "SC",
        "SE",
        "SP",
        "TO",
      ],
      selected: ["PE"],
      allowMultiple: false,
    },
    {
      label: "MUNICÍPIO",
      options: [
        "Recife",
        "Olinda",
        "Jaboatão dos Guararapes",
        "Paulista",
        "Camaragibe",
        "Cabo de Santo Agostinho",
        "Ipojuca",
        "Caruaru",
        "Petrolina",
      ],
      selected: ["Recife"],
      allowMultiple: false,
    },
  ],
};